#!/usr/bin/env python3

import sys
import os
import helpers

from analyzer import Analyzer
from termcolor import colored

def main():
    if len(sys.argv) != 2 :
        sys.exit("Usage: ./tweet <handle>")

    handle = sys.argv[1].strip('@')
    tweets = helpers.get_user_timeline(handle, 50)
    if tweets == None:
        sys.exit("Sumting went wong")

    positives = os.path.join(sys.path[0], "positive-words.txt")
    negatives = os.path.join(sys.path[0], "negative-words.txt")
    analyzer = Analyzer(positives, negatives)

    for tweet in tweets :
        score = analyzer.analyze(tweet)
        if score > 0.0:
            print(colored(":)", "green"))
        elif score < 0.0:
            print(colored(":(", "red"))
        else:
            print(colored(":|", "yellow"))

if __name__ == "__main__":
    main()
